services:
- type: web
  name: LinechatGPT
  env: python
  repo: https://github.com/chenghsaung/LinechatGPT.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn main:main
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
  - key: OPENAI_API_KEY
    sync: false
